sonar.projectKey=AntoniusAtefGhaly_Library-Management-System-FE
sonar.organization=antoniusatefghaly
sonar.host.url=https://sonarcloud.io

# Path to the source directories
sonar.sources=src

# Exclude test files and node_modules from analysis
sonar.exclusions=**/node_modules/**,**/*.spec.ts,src/environments/**

# Coverage report (if you decide to enable it later)
sonar.javascript.lcov.reportPaths=coverage/lcov.info
